---

- name: Instalando repo CentOS7
  yum:
   name: https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm
  when: 
   - ansible_distribution_major_version == "7"
   - ansible_distribution == "CentOS"

- name: instalando repo ubuntu1604
  apt:
   deb: https://apt.puppetlabs.com/puppet5-release-xenial.deb
  when: ansible_distribution_release == "xenial"
