
- name: criando usuarios padroes
  user:
   name: "{{item.nome}}"
   password: "{{item.senha}}"
   home: "/srv/{{item.nome}}"
  with_items:
   - {nome: luiz, senha: '$1$ERzRKPFs$.hIuNA7MbxyMfGrKqtuvL1' }
   - {nome: developer, senha: '$1$ERzRKPFs$.hIuNA7MbxyMfGrKqtuvL1' }
   - {nome: devops, senha: '$1$ERzRKPFs$.hIuNA7MbxyMfGrKqtuvL1' }
